name: hexlet-ci-app

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
      - run: make setup
      - run: make test
      - run: make lint